### ISSUE TITLE
Items/Blocks aren't compatible with crafttweaker rename/lore functions

### ISSUE THREAD

**Issue by xkforce** [Pyre540/colored-redstone#1]
I tried to use crafttweaker to make the item names more readable because the default is to color each item's color name with the color in question which makes it a lot harder to read than it could be.  The problem is that it doesn't actually work.  You can't use the rename etc. functions from crafttweaker to change the text color of these items:

The syntax is supposed to be something like this:
<modid:itemname>.displayName = "Example Text";

**Comment by Pyre540** [comment]
Unfortunately, it seems that CraftTweaker renaming is not working if you are displaying a name that is more than just simple value from language file. I suspect that CraftTweaker renaming is technicaly working but is overwritten by my mods values. 
You can check out version 1.0.1 of mod. I changed some colors to increase readability.

**Comment by xkforce** [comment]
I can see it's a bit better but the reason why I was trying to use crafttweaker to remove the coloration is because I am visually impaired.  Isn't there some way to let people that can read the colored text easily have it while letting people like me turn it off in the config if we need to?

**Comment by Pyre540** [comment]
I added option to enable/disable colored text in config. When disabled items/blocks names will be default white and tooltips default light gray.  You should be able to change tooltip color with CraftTweaker.
This change will be out in the next version of mod. Probably really soon :)

**Comment by xkforce** [comment]
Thank you!  This makes things so much better.

**Comment by Pyre540** [comment]
New version is out :)
You may need to delete the old configuration file when updating to properly generate a new one!
